use crate::domain::collection::Collection;
use std::fs;

pub fn generate_markdown(collections: &[Collection]) -> String {
    let mut md = String::new();
    md.push_str("# API Documentation\n\n");
    md.push_str("> Generated by **Postdad** 👟\n\n");

    for col in collections {
        md.push_str(&format!("## Collection: {}\n\n", col.name));

        let mut sorted_keys: Vec<_> = col.requests.keys().collect();
        sorted_keys.sort();

        for key in sorted_keys {
            if let Some(req) = col.requests.get(key) {
                md.push_str(&format!("### {}\n\n", key));
                md.push_str(&format!("**{}** `{}`\n\n", req.method, req.url));

                if let Some(headers) = &req.headers
                    && !headers.is_empty()
                {
                    md.push_str("#### Headers\n| Key | Value |\n|---|---|\n");
                    for (k, v) in headers {
                        md.push_str(&format!("| {} | {} |\n", k, v));
                    }
                    md.push('\n');
                }

                if let Some(body) = &req.body
                    && !body.trim().is_empty()
                {
                    md.push_str("#### Body\n");
                    // Attempt to detect language, default to json
                    let lang = if body.trim().starts_with('<') {
                        "xml"
                    } else {
                        "json"
                    };
                    md.push_str(&format!("```{}\n", lang));
                    md.push_str(body);
                    md.push_str("\n```\n\n");
                }

                if let Some(fd) = &req.form_data
                    && !fd.is_empty()
                {
                    md.push_str("#### Form Data\n| Key | Value | Is File |\n|---|---|---|\n");
                    for (k, v, is_file) in fd {
                        md.push_str(&format!("| {} | {} | {} |\n", k, v, is_file));
                    }
                    md.push('\n');
                }

                if let Some(gql) = &req.graphql_query
                    && !gql.trim().is_empty()
                {
                    md.push_str("#### GraphQL Query\n");
                    md.push_str("```graphql\n");
                    md.push_str(gql);
                    md.push_str("\n```\n\n");
                }
            }
        }
        md.push_str("---\n\n");
    }

    md
}

pub fn save_docs(collections: &[Collection]) -> std::io::Result<String> {
    let md = generate_markdown(collections);
    let path = "API_DOCS.md";
    fs::write(path, md)?;
    Ok(path.to_string())
}

pub fn generate_html(collections: &[Collection]) -> String {
    let mut html = String::new();

    // Header & CSS
    html.push_str(r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PostDad API Documentation</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-deep: #0b0b14;
            --bg-main: #0f101a;
            --bg-card: rgba(23, 25, 41, 0.7);
            --accent-glow: rgba(137, 180, 250, 0.15);
            --text-main: #e0e0e0;
            --text-dim: #949cbb;
            --accent: #89b4fa;
            --accent-gradient: linear-gradient(135deg, #89b4fa 0%, #b4befe 100%);
            --glass-border: rgba(255, 255, 255, 0.08);
            --code-bg: #11111b;
            
            --get: #a6e3a1;
            --post: #f9e2af;
            --put: #89b4fa;
            --delete: #f38ba8;
            --patch: #cba6f7;
        }

        * {
            box-sizing: border-box;
            scrollbar-width: thin;
            scrollbar-color: var(--glass-border) transparent;
        }

        body {
            font-family: 'Outfit', sans-serif;
            background-color: var(--bg-deep);
            background-image: 
                radial_gradient(at 0% 0%, rgba(137, 180, 250, 0.05) 0px, transparent 50%),
                radial_gradient(at 100% 100%, rgba(203, 166, 247, 0.05) 0px, transparent 50%);
            color: var(--text-main);
            margin: 0;
            display: flex;
            height: 100vh;
            overflow: hidden;
        }

        /* Sidebar */
        .sidebar {
            width: 320px;
            background: rgba(15, 16, 26, 0.8);
            backdrop-filter: blur(20px);
            border-right: 1px solid var(--glass-border);
            display: flex;
            flex-direction: column;
            z-index: 100;
        }

        .logo-container {
            padding: 30px 25px;
            background: linear-gradient(to bottom, rgba(137, 180, 250, 0.05), transparent);
            border-bottom: 1px solid var(--glass-border);
        }

        .logo {
            font-size: 1.8rem;
            font-weight: 700;
            background: var(--accent-gradient);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            letter-spacing: -0.5px;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .logo span {
            font-size: 1.2rem;
            opacity: 0.8;
            -webkit-text-fill-color: var(--text-dim);
        }

        .nav-scroll {
            flex: 1;
            overflow-y: auto;
            padding: 20px 10px;
        }

        .nav-collection {
            padding: 15px 15px 8px;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.75rem;
            color: var(--accent);
            letter-spacing: 1px;
            opacity: 0.8;
        }

        .nav-item {
            padding: 10px 15px;
            margin: 2px 8px;
            cursor: pointer;
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            display: flex;
            align-items: center;
            gap: 12px;
            text-decoration: none;
            color: var(--text-dim);
            font-size: 0.95rem;
            border-radius: 10px;
            border: 1px solid transparent;
        }

        .nav-item:hover {
            background: rgba(255, 255, 255, 0.03);
            color: var(--text-main);
            transform: translateX(5px);
            border-color: var(--glass-border);
        }

        .nav-item.active {
            background: var(--accent-glow);
            color: var(--accent);
            border-color: rgba(137, 180, 250, 0.3);
        }

        .method-badge {
            font-family: 'JetBrains Mono', monospace;
            font-size: 0.65rem;
            font-weight: 700;
            padding: 3px 8px;
            border-radius: 6px;
            text-transform: uppercase;
            min-width: 55px;
            text-align: center;
            box-shadow: 0 2px 10px rgba(0,0,0,0.2);
        }

        /* Main Content */
        .main {
            flex: 1;
            padding: 0;
            overflow-y: auto;
            scroll-behavior: smooth;
            background: var(--bg-deep);
        }

        .content-container {
            max-width: 900px;
            margin: 0 auto;
            padding: 60px 40px;
        }

        .endpoint {
            margin-bottom: 80px;
            background: var(--bg-card);
            backdrop-filter: blur(10px);
            border: 1px solid var(--glass-border);
            border-radius: 24px;
            padding: 40px;
            box-shadow: 0 20px 50px rgba(0,0,0,0.3);
            transition: transform 0.3s ease;
        }

        .endpoint:hover {
            transform: translateY(-5px);
            border-color: rgba(137, 180, 250, 0.2);
        }

        .endpoint-header {
            display: flex;
            flex-direction: column;
            gap: 20px;
            margin-bottom: 30px;
        }

        .title-row {
            display: flex;
            align-items: center;
            gap: 20px;
        }

        .endpoint-title {
            font-size: 2.2rem;
            font-weight: 700;
            letter-spacing: -0.5px;
            color: #fff;
        }

        .endpoint-url-container {
            display: flex;
            align-items: center;
            background: rgba(0, 0, 0, 0.3);
            padding: 4px;
            border-radius: 12px;
            border: 1px solid var(--glass-border);
        }

        .endpoint-url {
            font-family: 'JetBrains Mono', monospace;
            padding: 10px 15px;
            font-size: 0.95rem;
            color: var(--accent);
            word-break: break-all;
        }

        .section {
            margin-top: 40px;
        }

        .section-header {
            display: flex;
            align-items: center;
            gap: 12px;
            margin-bottom: 20px;
        }

        .section-title {
            font-size: 1.1rem;
            font-weight: 600;
            color: var(--text-dim);
            text-transform: uppercase;
            letter-spacing: 1.5px;
        }

        .section-line {
            flex: 1;
            height: 1px;
            background: linear-gradient(to right, var(--glass-border), transparent);
        }

        table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0;
            margin-bottom: 25px;
            background: rgba(0, 0, 0, 0.2);
            border-radius: 14px;
            overflow: hidden;
            border: 1px solid var(--glass-border);
        }

        th, td {
            text-align: left;
            padding: 16px 20px;
            border-bottom: 1px solid var(--glass-border);
        }

        th {
            background: rgba(255, 255, 255, 0.03);
            color: var(--accent);
            font-weight: 600;
            font-size: 0.85rem;
            text-transform: uppercase;
        }

        tr:last-child td {
            border-bottom: none;
        }

        pre {
            background: #0d0e14;
            padding: 24px;
            border-radius: 16px;
            overflow-x: auto;
            border: 1px solid var(--glass-border);
            font-family: 'JetBrains Mono', monospace;
            font-size: 0.9rem;
            line-height: 1.6;
            color: #a6e3a1;
            box-shadow: inset 0 2px 10px rgba(0,0,0,0.3);
        }

        /* Method Colors */
        .badge-get { background: var(--get); color: #111; }
        .badge-post { background: var(--post); color: #111; }
        .badge-put { background: var(--put); color: #111; }
        .badge-delete { background: var(--delete); color: #111; }
        .badge-patch { background: var(--patch); color: #111; }

        /* Animation */
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .endpoint {
            animation: fadeIn 0.6s cubic-bezier(0.23, 1, 0.32, 1) both;
        }

        ::-webkit-scrollbar {
            width: 8px;
        }

        ::-webkit-scrollbar-thumb {
            background: var(--glass-border);
            border-radius: 10px;
        }

        ::-webkit-scrollbar-thumb:hover {
            background: rgba(255, 255, 255, 0.15);
        }
    </style>
</head>
<body>

<div class="sidebar">
    <div class="logo-container">
        <div class="logo">⚡ PostDad <span>DOCS</span></div>
    </div>
    <div class="nav-scroll">
"#);

    // Generate Sidebar
    for col in collections {
        html.push_str(&format!(
            r#"<div class="nav-collection">{}</div>"#,
            col.name
        ));
        let mut sorted_keys: Vec<_> = col.requests.keys().collect();
        sorted_keys.sort();

        for key in sorted_keys {
            if let Some(req) = col.requests.get(key) {
                let method_class = req.method.to_lowercase();
                let anchor = format!("{}-{}", col.name, key)
                    .replace(" ", "-")
                    .to_lowercase();

                html.push_str(&format!(
                    r##"<a href="#{}" class="nav-item">
                        <span class="method-badge badge-{}">{}</span>
                        <span>{}</span>
                    </a>"##,
                    anchor, method_class, req.method, key
                ));
            }
        }
    }

    html.push_str(r#"</div></div><div class="main"><div class="content-container">"#);

    // Generate Content
    for (c_idx, col) in collections.iter().enumerate() {
        let mut sorted_keys: Vec<_> = col.requests.keys().collect();
        sorted_keys.sort();

        for key in sorted_keys {
            if let Some(req) = col.requests.get(key) {
                let anchor = format!("{}-{}", col.name, key)
                    .replace(" ", "-")
                    .to_lowercase();
                let method_class = req.method.to_lowercase();
                let delay = (c_idx * 10).to_string(); // Simple staggered animation

                html.push_str(&format!(
                    r#"<div id="{}" class="endpoint" style="animation-delay: {}ms">"#,
                    anchor, delay
                ));

                // Header
                html.push_str(r#"<div class="endpoint-header">"#);
                html.push_str(r#"<div class="title-row">"#);
                html.push_str(&format!(r#"<span class="method-badge badge-{}" style="font-size: 0.9rem; padding: 6px 12px; min-width: 70px;">{}</span>"#, method_class, req.method));
                html.push_str(&format!(r#"<div class="endpoint-title">{}</div>"#, key));
                html.push_str("</div>");

                html.push_str(r#"<div class="endpoint-url-container">"#);
                html.push_str(&format!(r#"<div class="endpoint-url">{}</div>"#, req.url));
                html.push_str("</div>");
                html.push_str("</div>");

                // Headers
                if let Some(headers) = &req.headers
                    && !headers.is_empty()
                {
                    html.push_str(r#"<div class="section"><div class="section-header"><div class="section-title">Request Headers</div><div class="section-line"></div></div>"#);
                    html.push_str(
                        "<table><thead><tr><th>Key</th><th>Value</th></tr></thead><tbody>",
                    );
                    for (k, v) in headers {
                        html.push_str(&format!(
                            "<tr><td><code>{}</code></td><td>{}</td></tr>",
                            k, v
                        ));
                    }
                    html.push_str("</tbody></table></div>");
                }

                // Body
                if let Some(body) = &req.body
                    && !body.trim().is_empty()
                {
                    html.push_str(r#"<div class="section"><div class="section-header"><div class="section-title">Request Body</div><div class="section-line"></div></div>"#);
                    let escaped = body.replace("<", "&lt;").replace(">", "&gt;");
                    html.push_str(&format!("<pre><code>{}</code></pre></div>", escaped));
                }

                // Form Data
                if let Some(fd) = &req.form_data
                    && !fd.is_empty()
                {
                    html.push_str(r#"<div class="section"><div class="section-header"><div class="section-title">Form Data</div><div class="section-line"></div></div>"#);
                    html.push_str("<table><thead><tr><th>Key</th><th>Value</th><th>Type</th></tr></thead><tbody>");
                    for (k, v, is_file) in fd {
                        let type_str = if *is_file { "File" } else { "Text" };
                        html.push_str(&format!("<tr><td><code>{}</code></td><td>{}</td><td><span style='opacity:0.6'>{}</span></td></tr>", k, v, type_str));
                    }
                    html.push_str("</tbody></table></div>");
                }

                // GraphQL
                if let Some(gql) = &req.graphql_query
                    && !gql.trim().is_empty()
                {
                    html.push_str(r#"<div class="section"><div class="section-header"><div class="section-title">GraphQL Query</div><div class="section-line"></div></div>"#);
                    let escaped = gql.replace("<", "&lt;").replace(">", "&gt;");
                    html.push_str(&format!("<pre><code>{}</code></pre></div>", escaped));
                }

                html.push_str("</div>"); // Close endpoint
            }
        }
    }

    html.push_str(
        r#"</div></div>
    <script>
        // Simple scroll spy for active navigation
        const endpoints = document.querySelectorAll('.endpoint');
        const navItems = document.querySelectorAll('.nav-item');
        const main = document.querySelector('.main');

        main.addEventListener('scroll', () => {
            let current = '';
            endpoints.forEach(endpoint => {
                const sectionTop = endpoint.offsetTop;
                if (main.scrollTop >= sectionTop - 100) {
                    current = endpoint.getAttribute('id');
                }
            });

            navItems.forEach(item => {
                item.classList.remove('active');
                if (item.getAttribute('href').slice(1) === current) {
                    item.classList.add('active');
                }
            });
        });
    </script>
    </body></html>"#,
    );
    html
}

pub fn save_html_docs(collections: &[Collection]) -> std::io::Result<String> {
    let html = generate_html(collections);
    let path = "API_DOCS.html";
    fs::write(path, html)?;
    Ok(path.to_string())
}
