use crate::collection::Collection;
use std::fs;

pub fn generate_markdown(collections: &[Collection]) -> String {
    let mut md = String::new();
    md.push_str("# API Documentation\n\n");
    md.push_str("> Generated by **Postdad** 👟\n\n");

    for col in collections {
        md.push_str(&format!("## Collection: {}\n\n", col.name));

        let mut sorted_keys: Vec<_> = col.requests.keys().collect();
        sorted_keys.sort();

        for key in sorted_keys {
            if let Some(req) = col.requests.get(key) {
                md.push_str(&format!("### {}\n\n", key));
                md.push_str(&format!("**{}** `{}`\n\n", req.method, req.url));

                if let Some(headers) = &req.headers {
                    if !headers.is_empty() {
                        md.push_str("#### Headers\n| Key | Value |\n|---|---|\n");
                        for (k, v) in headers {
                            md.push_str(&format!("| {} | {} |\n", k, v));
                        }
                        md.push_str("\n");
                    }
                }

                if let Some(body) = &req.body {
                    if !body.trim().is_empty() {
                        md.push_str("#### Body\n");
                        // Attempt to detect language, default to json
                        let lang = if body.trim().starts_with('<') { "xml" } else { "json" };
                        md.push_str(&format!("```{}\n", lang));
                        md.push_str(body);
                        md.push_str("\n```\n\n");
                    }
                }
                
                if let Some(fd) = &req.form_data {
                    if !fd.is_empty() {
                        md.push_str("#### Form Data\n| Key | Value | Is File |\n|---|---|---|\n");
                        for (k, v, is_file) in fd {
                             md.push_str(&format!("| {} | {} | {} |\n", k, v, is_file));
                        }
                         md.push_str("\n");
                    }
                }

                if let Some(gql) = &req.graphql_query {
                    if !gql.trim().is_empty() {
                        md.push_str("#### GraphQL Query\n");
                        md.push_str("```graphql\n");
                        md.push_str(gql);
                        md.push_str("\n```\n\n");
                    }
                }
            }
        }
        md.push_str("---\n\n");
    }

    md
}

pub fn save_docs(collections: &[Collection]) -> std::io::Result<String> {
    let md = generate_markdown(collections);
    let path = "API_DOCS.md";
    fs::write(path, md)?;
    Ok(path.to_string())
}
